# Generated by Django 4.1 on 2023-01-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_to', models.CharField(max_length=140)),
                ('contact_number', models.CharField(max_length=30)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='houses.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
