# Generated by Django 4.1 on 2023-07-01 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactnumber",
            table="contact",
        ),
    ]
