# Generated by Django 4.1 on 2023-01-13 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_houses',
            field=models.ManyToManyField(blank=True, related_name='users', to='houses.apartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apt_number',
            field=models.CharField(blank=True, help_text='아파트 동', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(blank=True, help_text='아파트 호수', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='이름', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='전화번호', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)([0-9]{3,4})([0-9]{4})$')]),
        ),
    ]
