# Generated by Django 4.1 on 2023-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=False, help_text="주민 확인 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, help_text="이름(실명)", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(blank=True, help_text="유저 프로필 이미지"),
        ),
    ]
