# Generated by Django 4.1 on 2023-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.FileField(blank=True, help_text="유저 프로필 이미지", upload_to=""),
        ),
    ]
