version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ./entrypoint.prod.sh
    volumes:
      - ./:/home/appuser/
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --requirepass apt_management_password
    ports:
      - "6000:6000"
