version: "3"

services:
  web:
    build: .
    hostname: django
    container_name: django
    command: ./entrypoint.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    hostname: postgres
    container_name: postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/logs:/var/log/
    env_file:
      - ./.env.postgres.dev
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    command: redis-server --requirepass apt_management_password
    ports:
      - "6000:6379"

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
    depends_on:
      - loki
      - prometheus

  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - ./logs:/var/log/django/
      - ./postgres/logs:/var/log/postgresql/
    command: --config.file=/etc/promtail/promtail.yml
    depends_on:
      - web

  loki:
    image: grafana/loki:2.5.0
    hostname: loki
    container_name: loki
    ports:
      - "3100:3100"
    # volumes:
    #   - ./loki/:/loki/
    # command: -config.file=/loki/local-config.yml
    depends_on:
      - promtail

volumes:
  postgres_data:
