version: "3"

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/appuser/static
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ./settings.sh
    volumes:
      - ./:/home/appuser/
      - static_volume:/home/appuser/static
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.4-alpine
    command: postgres -c "max_connectios=300"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres.prod
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command: redis-server --requirepass apt_management_password
    ports:
      - "6000:6000"

volumes:
  postgres_data:
  static_volume:
