# Generated by Django 4.1 on 2023-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_as1_apartment_address_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='kapt_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
