# Generated by Django 4.1 on 2023-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0003_alter_apartment_kapt_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="address_do",
            field=models.CharField(help_text="도", max_length=200),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address_dong",
            field=models.CharField(help_text="읍면동", max_length=200),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address_li",
            field=models.CharField(blank=True, help_text="리", max_length=200),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address_si",
            field=models.CharField(help_text="시군구", max_length=200),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="bjd_code",
            field=models.CharField(help_text="법정동코드", max_length=200),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="kapt_code",
            field=models.CharField(help_text="단지코드", max_length=200),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="kapt_name",
            field=models.CharField(db_index=True, help_text="단지명", max_length=200),
        ),
    ]
