# Generated by Django 4.1 on 2023-07-01 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0004_alter_apartment_address_do_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apartment",
            table="apartment",
        ),
    ]
