# Generated by Django 4.1 on 2023-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0005_alter_apartment_table"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["kapt_code"], name="apartment_kapt_co_654a08_idx"
            ),
        ),
    ]
