global:
  scrape_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: django-metrics
    static_configs:
      - targets: ["web:8000"]
        labels:
          app: django

  - job_name: flower-metrics
    static_configs:
      - targets: ["flower:5555"]
