# Generated by Django 4.1 on 2023-08-19 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_alter_feed_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ["-created_at"]},
        ),
    ]
