# Generated by Django 4.1 on 2023-07-01 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="photo",
            table="photo",
        ),
        migrations.AlterModelTable(
            name="video",
            table="video",
        ),
    ]
