# Generated by Django 4.1 on 2023-01-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='current_status',
            field=models.BooleanField(default=False),
        ),
    ]
